version: '3'

services:
  postgresql:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: simple-bank-account-db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - "8000:8000"